language: R
r:
# - oldrel
  - release
  - devel
sudo: required

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get -q update
  - sudo aptitude install -y libgdal-dev
  - sudo aptitude install -y libproj-dev
  - sudo apt-get install -y libudunits2-dev
  - sudo apt-get install -y libgeos-dev
  - sudo apt-get install libssh2-1-dev
  - sudo apt-get install netcdf-bin

  - R -e 'install.packages("devtools")'

r_github_packages:
  - 16EAGLE/getSpatialData
  - MBalthasar/rHarmonics

install:
  - R -e 'devtools::install_deps(dep = T)'

script:
  - R CMD build .
  - R CMD check *tar.gz --no-tests
